# Coral Server Configuration for AI Dev Squad
# This configuration file sets up Coral Server for local development

# Server configuration
[server]
port = 5555
host = "0.0.0.0"

# MCP Server settings
[mcp]
enabled = true
transport = "stdio"

# Docker configuration for agent containers
[docker]
enabled = true
socket_path = "/var/run/docker.sock"

# Logging configuration
[logging]
level = "INFO"
format = "json"

# Security settings
[security]
enable_auth = false  # Disabled for local development
cors_origins = ["http://localhost:3000", "http://localhost:8000"]

# Rate limiting
[rate_limit]
enabled = true
requests_per_minute = 100

# Registry settings
[registry]
enable_marketplace = true
allow_external_agents = true